### ISSUE TITLE
change format fq to fa in all samples

### ISSUE THREAD

**Issue by IsauraRReinhold** [IsauraRReinhold/Disocactus_transcriptome#12]
```

#!/bin/bash
# This script converts fq data to fasta format and move and save in out dir.
# Run this script from directory ~/bin/ and the data are in ~/data/DE_clean/
#$ -cwd
#$ -j y
#$ -V                    #export environment var
#$ -N fq_to_fa             #name Job
echo "************************************************************"
echo "*********" $HOSTNAME " ****** JOB_ID=" $JOB_ID "  *************"
echo "************************************************************"

#make out dir

mkdir -p ../data/DE_fasta/

mkdir -p ../data/DS_fasta/

#loop convert fq files in fasta files

for i in DE_clean DS_clean; do #folders with fq samples

  for k in `ls ../data/${i}/ | grep ".fq" | uniq`;  do
  echo ${k}

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_1P.fq > ${k}_1P.fasta #convert 1P.fq to 1P.fasta

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_2P.fq > ${k}_2P.fasta #convert 2P.fq to 2P.fasta

done
  done
  
#loop to move fasta files to out directories

for i in DE_clean DS_clean; do #fasta files are saved here

  cd ../data/${i} #enter to folder
  
  for k in `ls ../data/${i}/ | grep ".fasta" | sed "s/_1.fa//"| sed "s/_2.fa//" | uniq` ; do
  echo ${k}

mv DE*.fasta  ../data/DE_fasta/

mv DS*.fasta  ../data/DS_fasta/

  done 
done

```

**Comment by IsauraRReinhold** [comment]
cuando corro la primera parte del script convierte todos tanto los Paired como Unpaired y no les cambia el nombre, solo lo agrega

```
DE1-2PA_1P.fq_2P.fasta  DE1-2PA_1U.fq.fasta

```

**Comment by cristoichkov** [comment]
Creo que ya vi el problema, 

```
for i in DE_clean DS_clean; do #folders with fq samples

  for k in `ls ../data/${i}/ | grep ".fq" | uniq`;  do ## <- aqui esta el problema
  echo ${k}

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_1P.fq > ${k}_1P.fasta #convert 1P.fq to 1P.fasta

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_2P.fq > ${k}_2P.fasta #convert 2P.fq to 2P.fasta

done
  done
```
`ls ../data/${i}/` ver los archivos que estan en la carpeta
`grep ".fq"` buscar los archivos con terminacion .fq
`uniq` eliminar los nombres duplicados
te falta eliminar la terminacion .fq con sed
asi como esta te va a sacar esto
DE3-8PC_1P.fq
DE3-8PC_1U.fq
DE3-8PC_2P.fq
DE3-8PC_2U.fq
entonces en tu siguiente parte 
 `sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_1P.fq`

lo que esta hacuendo es cambiar los caracteres con sed en el archivo siguiente
`../data/${i}/DE3-8PC_1P.fq_1P.fq` aqui esta el error por que no le quitaste la terminacion .fq, entonces no encuentra el archivo en primera y la segunda parte `> ${k}_1P.fasta` lo que hace es agregar solo el nombre DE3-8PC_1P.fq_1P.fasta

```
for i in DE_clean DS_clean; do #folders with fq samples

  for k in `ls ../data/${i}/ | grep ".fq" |  | sed "s/.fq//" | uniq`;  do ## tienes que agregar un sed antes de uniq para quitar .fq
  echo ${k}

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_1P.fq > ${k}_1P.fasta #convert 1P.fq to 1P.fasta

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_2P.fq > ${k}_2P.fasta #convert 2P.fq to 2P.fasta

done
  done
```

**Comment by IsauraRReinhold** [comment]
Ahora la segunda parte es moverlos pero no lo hace!!

``
#loop to move fasta files to out directories

for i in DE_clean DS_clean; do #fasta files are saved here

  cd ../data/${i} #enter to folder
  
  for k in `ls ../data/${i}/ | grep ".fasta" | sed "s/_1.fa//"| sed "s/_2.fa//" | uniq` ; do
  echo ${k}

mv DE*.fasta  ../data/DE_fasta/

mv DS*.fasta  ../data/DS_fasta/

  done 
done
``

**Comment by cristoichkov** [comment]
La segunda parte de tu script tambien esta mal 
```
#loop to move fasta files to out directories

for i in DE_clean DS_clean; do #fasta files are saved here

  cd ../data/${i} #enter to folder ## aqui 
  
  for k in `ls ../data/${i}/ | grep ".fasta" | sed "s/_1.fa//"| sed "s/_2.fa//" | uniq` ; do
  echo ${k}

mv DE*.fasta  ../data/DE_fasta/

mv DS*.fasta  ../data/DS_fasta/

  done 
done
```

`cd ../data/${i} #enter to folder ` cambiar al directorio 
entonces en la siguinete parte 
` for k in `ls ../data/${i}/ | grep ".fasta" | sed "s/_1.fa//"| sed "s/_2.fa//" | uniq` ; do
  echo ${k}` se supone que ya estas en la carpeta `./data/${i}/`, esta demas volver a repetir esto
Revisa tus rutas ya que al final del script tal vez en el ultimo done vas a tener que regresar a bin. te hace falta un regreso `cd ../../bin` creo

**Comment by IsauraRReinhold** [comment]
ok, entonces si quiero uno para concatenar los fasta se va a parecer mucho, no?

**Comment by IsauraRReinhold** [comment]
ya probé es script y dice esto:

DS1-13PC__2U
sed: no se puede leer ../data/DS_clean/DS1-13PC__2U_1P.fq: No existe el archivo o el directorio
sed: no se puede leer ../data/DS_clean/DS1-13PC__2U_2P.fq: No existe el archivo o el directorio

**Comment by cristoichkov** [comment]
Como se llaman tus datos? y cuales son los que quieres mover?

**Comment by IsauraRReinhold** [comment]
Así quedó: mis datos se llaman xxx_1P.fq, xxx_2P.fq, xxx_1U.fq, xxx_2U.fq y quiero solo convertir los 1P y 2P en fasta y moverlos a la carpeta fasta
```
for i in DE_clean DS_clean; do #folders with fq samples

  for k in `ls ../data/${i}/ | grep ".fq" | sed "s/_1P.fq//"| sed "s/_2P.fq//" | uniq` ;  do ## tienes que agregar un sed antes de uniq para quitar .fq
  echo ${k}

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_1P.fq > ${k}_1P.fasta #convert 1P.fq to 1P.fasta

sed -n '1~4s/^@/>/p;2~4p' ../data/${i}/${k}_2P.fq > ${k}_2P.fasta #convert 2P.fq to 2P.fasta

done
  done
```

**Comment by cristoichkov** [comment]
Creo que quedariasí

```
for i in DE DS; do #folders with fq samples

  for k in `ls ../data/${i}_clean/ | grep "P.fq" | sed "s/_1P.fq//"| sed "s/_2P.fq//" | uniq` ;  do ## tienes que agregar un sed antes de uniq para quitar .fq
  echo ${k}

  sed -n '1~4s/^@/>/p;2~4p' ../data/${i}_clean/${k}_1P.fq > ${k}_1P.fasta #convert 1P.fq to 1P.fasta

  mv ${k}_1P.fasta ../data/${i}_fasta/

  sed -n '1~4s/^@/>/p;2~4p' ../data/${i}_clean/${k}_2P.fq > ${k}_2P.fasta #convert 2P.fq to 2P.fasta

  mv ${k}_2P.fasta ../data/${i}_fasta/

done
  done
```
