### ISSUE TITLE
Gene  Annotation using edgeR and kegga function

### ISSUE THREAD

**Issue by IsauraRReinhold** [IsauraRReinhold/Disocactus_transcriptome#23]
### Hi every one!! 

 I made the differencial expression analysis from my RNA-seq data  following different tutorials like [from reads to genes](https://www.bioconductor.org/packages/release/workflows/vignettes/RnaSeqGeneEdgeRQL/inst/doc/edgeRQL.html). Finally I got the DE expression results and expression clusters.

Know I would like to do a KEGG annotation analysis. EdgeR has a function called `kegga` that makes this type of analysis.

`kegga` uses a gene data set which has to be in a vector format and an specific species data base, which in my case is *Arabidosis thaliana*.

The gene set I have to use as an input is the result from  `glmTreat` or `glmQLFTest` functions.

In my case this gene data set is called ` qlf.BvsA.lfc1` in my [R script](https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/bin/dif_exp_DE.r).

----

### In order to run the KEGG analysis I use the following commands

```
#kegga function to annotate my genes using Arabidopsis thaliana "At"

k<-kegga(qlf.BvsA.lfc1, species = "At")

```
### When I run the `kegga` function I have the following error

`Error in kegga.default(de = DEGenes, universe = universe, ...) : 
  Pathways do not overlap with universe`

### When I make a `head(k)`, I can see the following table. 

![image](https://user-images.githubusercontent.com/35971939/104252785-80c18500-5438-11eb-81cc-5aebd9c294ba.png)

### But in this table we are missing the `up` and `down` regulated colomns as is shown in the following example.

![image](https://user-images.githubusercontent.com/35971939/104252874-c1b99980-5438-11eb-8198-dce2aac42ee9.png)

**Comment by arihelrnan** [comment]
The error messages its similary to the report in (https://support.bioconductor.org/p/105958/). We can try apllicated this solution.

**Comment by IsauraRReinhold** [comment]
kegga(de, geneid = rownames(de), FDR = 0.05, trend = FALSE, ...)

USAGE

`de`	an DGELRT or DGEExact object.

`geneid`	
gene IDs. Either a character vector of length nrow(de) or the name of the column of de$genes containing the Gene IDs.

FDR	``
false discovery rate cutoff for differentially expressed genes. Numeric value between 0 and 1.

`trend`	
adjust analysis for gene length or abundance? Can be logical, or a numeric vector of covariate values, or the name of the column of de$genes containing the covariate values. If TRUE, then de$AveLogCPM is used as the covariate.

...	
any other arguments are passed to goana.default or kegga.default.

**Comment by camillethuyentruong** [comment]
In the [edgeR](https://www.bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf) documentation, several functions are implemented to annotate genes, for example:

The `romer()` function performs a gene set enrichment analysis. It implements a GSEA approach [39] based on rotation instead of permutation. Unlike `goana()` and `kegga()`, the gene set tests are not limited to GO terms or KEGG pathways. **Any pre-defined gene set can be used**, for example MSigDB gene sets. A common application is to use a set of DE genes that was defined from an analysis of an independent data set

**Comment by IsauraRReinhold** [comment]
Possible solution

https://support.bioconductor.org/p/101417/

**Comment by IsauraRReinhold** [comment]
https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/out/dif_exp_DE/dif_exp_DE.html

**Comment by camillethuyentruong** [comment]
Looking at the resulting table, it seems that only the differential expression is lacking while the gene annotation is working. Does your input file `qlf.BvsA.lfc1`contain the log fold change data?

**Comment by arihelrnan** [comment]
For the error messages, you can try run `kegga` with argument `species.KEGG`. This argument allows species names to be specifie. For more infomation watch R Documentation [here](https://www.rdocumentation.org/packages/limma/versions/3.28.14/topics/goana)

**Comment by IsauraRReinhold** [comment]
Usage

## S3 method for class 'DGEList'
romer(y, index, design=NULL, contrast=ncol(design), ...)

y | DGEList object.

index | list of indices specifying the rows of y in the gene sets. The list can be made using ids2indices.
design | design matrix. Defaults to y$design or, failing that, to model.matrix(~y$samples$group).
contrast | contrast for which the test is required. Can be an integer specifying a column of design, or the name of a column of design, or else a contrast vector of length equal to the number of columns of design.
... | other arguments are passed to romer.default. For example, the number of rotations nrotcan be increased from the default of 9999 to increase the resolution of the p-values.

**Comment by valeriafloral** [comment]
In the [edgeR documentation](https://www.bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf) they give an example of `goana` and `kegga` usage, but they used the `glmQLFTest` instead `glmFit`. 

> Suppose we want to identify GO terms and KEGG pathways that are over-represented in group 2 compared to group 1 from the previous example in Section 2.11.3 assuming the samples are collected from mice. We use the following commands:

```
> qlf <- glmQLFTest(fit, coef=2)
> go <- goana(qlf, species="Mm")
> topGO(go, sort="up")
> keg <- kegga(qlf, species="Mm")
> topKEGG(keg, sort="up")
```

**Comment by IsauraRReinhold** [comment]
Following the comments I try the next:

k<-kegga(qlf.BvsA.lfc1, geneid = qlf.BvsA.lfc1$"genes", species = "At")


Error in kegga.DGELRT(qlf.BvsA.lfc1, geneid = qlf.BvsA.lfc1$genes, species = "At") : 
  Column c("TRINITY_DN19622_c0_g1_i1", "TRINITY_DN19624_c0_g2_i1", "TRINITY_DN19624_c0_g1_i2", "TRINITY_DN19614_c0_g1_i1", "TRINITY_DN19638_c0_g1_i1", "TRINITY_DN19638_c0_g2_i1", "TRINITY_DN19673_c0_g1_i2", "TRINITY_DN19664_c0_g1_i1", "TRINITY_DN19679_c0_g1_i1", "TRINITY_DN19674_c0_g1_i1", "TRINITY_DN19603_c0_g1_i1", "TRINITY_DN19693_c0_g1_i1", "TRINITY_DN19654_c0_g1_i1", "TRINITY_DN19632_c0_g1_i1", "TRINITY_DN19607_c0_g1_i1", "TRINITY_DN19658_c0_g1_i1", "TRINITY_DN19621_c0_g1_i1", "TRINITY_DN19621_c0_g1_i2", 
"TRINITY_DN19667_c0_g1_i1", "TRINITY_DN19608_c0_g1_i1", "TRINITY_DN19608_c0_g1_i2", "TRINITY_DN19625_c0_g1_i1", "TRINITY_DN19625_c0_g1_i2", "TRINITY_DN19697_c0_g1_i1", "TRINITY_DN19605_c0_g1_i2", "TRINITY_DN19647_c0_g2_i1", "TRINITY_DN19647_c0_g1_i2", "TRINITY_DN19653_c0_g2_i2", "TRINITY_DN19687_c0_g1_i1", "TRINITY_DN19678_c0_g1_i1", "TRINITY_DN19627_c0_g1_i5", "TRINITY_DN19690_c0_g1_i1", "TRINITY_DN19675_c0_g1_i1", "TRINITY_DN19613_c0_g1_i1", "TRINITY_DN19613_c0_g2_i1",

**Comment by IsauraRReinhold** [comment]
following exactly the tutorial I have this result

test_annot<-kegga(tr, species = "At")
Error in kegga.default(tr, species = "At") : 
  components of de should be vectors

**Comment by valeriafloral** [comment]
In the tutorial, for using `kega` they use:

```
 fit <- glmQLFit(y, design, robust=TRUE)
 tr <- glmTreat(fit, contrast=B.LvsP, lfc=log2(1.5))
keg <- kegga(tr, species="Mm")
```

You used

```
fit <- glmQLFit(edgeRlist_DE, design, robust=TRUE)
k<-kegga(qlf.BvsA.lfc1, species = "At")
```

Your `**qlf.BvsA.lfc1**` object was was made differently

It seems that their `**tr**` object is not the same as your `**qlf.BvsA.lfc1**` object, you could try to use an object equal to their `**tr**` object.

**Comment by camillethuyentruong** [comment]
In the tutorial [from reads to genes](https://www.bioconductor.org/packages/devel/workflows/vignettes/RnaSeqGeneEdgeRQL/inst/doc/edgeRQL.html), you first need to generate a table using
`table <- glmTreat(fit, contrast=B.LvsP, lfc=log2(1.5))`

This input table already contains the differential expression values of genes for which kegga then perform gene annotation. Kegga only annotate the genes (no additional differential expression analysis) so the problem probably comes from the input table.

**Comment by IsauraRReinhold** [comment]
I can't resolve the issue because I need the functional annotation of my data.
