### ISSUE TITLE
Comments to improve repo organization, README and scritps

### ISSUE THREAD

**Issue by AliciaMstt** [IsauraRReinhold/Disocactus_transcriptome#24]
Hi. Your repo is looking good, but the following points need attention:

README:

- [x] Even if you are not presenting your sequencing data due to the size, you should briefly mention how is it named and structured in your README. Then say that it will be available in a data repository when this is published. But please describe it.   
- [x] You need to better explain your measurements data:
* What is each file? (or each common set of files, you don't need to explain all of them, but at least tell us if they are different samples or how to understand file names.
* What does each column of your measurements files mean? Min, Max of what? What are the units?
- [x] Mention what kind of sequencing and library preparation you did (Illumina? Pair end? etc) and of how many samples and tissues.
- [x] `07.trinity_assembly` is missing .sh at the end
- [x] Explain your sample code names, do they follow a pattern?
- [x] The project_info directory has very relevant information, like the one in Disocactus_project.md. However it is somewhat hidden in the README. I recommend mentioning it also earlier in the README, maybe as part of the introduction. Something like: More details of the experimental design and lab methodology are available at --LINK to relevant md in project info--.
- [x] The file is called `supertranscripts.md` not `Supertranscripts.md`. And I recommend adding a link to it.
- [x] Similarly to how you described the scripts, all data and metadata files should be briefly listed and explained. 
- [x] Columns of all data and metadata files should also be briefly explained in the  README. For instance you mention in file `Diso_code.csv` a variable called `stage`. But what does it mean stage 1 or 2? Also in In file `Diso_code.csv` what is the `flower number` variable? It is not clear if you refer to the number of flowers a plant has, or if you are referring to the flower tagged with the number 9. What is the sample_replicate_name in `samples.tx`?

Scritps:

- [x] You have  absolute paths in your scripts `12.DS_abun_est.sh` and `13.count_expr_trans.sh`, `busco_figure.r` . Please change them to relative paths. 
 
If this is not possible for some weird reason (you will need to convince us why in the comments of this issue), then explain it at the begging of the script, and use a variable so that users can change the path easier. eg:

```
# Data of this script is outside the repository. Please change the following variable to the path where you stored the data.
data="/media/cris/Isaura/EpiDiso/out/DS_k_quants"
```

- [x] script `13.count_expr_trans.sh`: the file`count_matrix_features_given_MIN_TPM_threshold.pl` seems to be a perl function that should be part of your GitHub repository. Please add it to bin and document it accordingly. If it is a function someone else made and you cannot share it for some obscure reason, then mention it in your README, add the contact of the person who can provide it. You can add it your gitignore but have it in your local bin.
- [x] All your R scripts need better documentation, several steps or chunks of code are not commented, specially when you are trying several plots.

Repo organization:

- [x] You have a directory called measures, but "measures" is a verb, I think you meant "measurements" which is a noun. 
- [x] Add `.Rhistory` and `.RData` to your `gitignore` and delete them from your Github.
- [x] Why some of your r scritps are not numbered? This is confusing, please number them as the rest of your scripts.

General:

- [x] Check for typos and spelling mistakes. For instance "thise", "script to crate", "stimate" in your README. Although we are not grading the English, it is important that for you to avoid spelling mistakes and obvious typos. You can install an English spelling corrector in your browser, open the md file to edit in Github and that will highlight any errors you have.
- [x] The correct word is species, not specie. It is singular even if it ends with an s. Like tijeras en español. 
- [x] I recommend avoiding spaces in variables names in your data and metadata. For instance you can change `Sample code` for `sample_code`

Summary in md:
You are missing a short md summary discussing your main results and advances.

**Comment by IsauraRReinhold** [comment]
to mention what kind of sequencing and library preparation I used, I will add to my README a subtitle called **data information**

**Comment by IsauraRReinhold** [comment]
I followed all the recommendations to improve my repository

1. I added a new section in the README file called data information where you will find information about samples, such as library type, sequencing platform, and so on.
2. I explained the content of the measures
3. To better explain my sample code, I added a section with a figure that explains the pattern of my sample code.
4. The folder named info_project is now mentioned in the README in the background section, with a link.
5. I also added a link to the supertrancrip.md file in the README.
6. I tried to explain my metada files in a  better way.
7. Absolute paths were modified in some scripts.
8. I added new comments in my R scripts, some of them were in Spanish and they were translated.
9. The folder called measures  now is called measurements.
10. .Rdata and .Rhistory now are in the .gitignore file.
11. R scripts are now numbered like the .sh scripts.
12. Spaces in some names in data and metadata have been removed and replaced by an underscore.
13. The summary.md will be saved in the project_info folder.

Thanks for all the comments, my repository is definitely better now

**Comment by IsauraRReinhold** [comment]
Finally I check the typos in the README and the summary
