### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by camillethuyentruong** [IsauraRReinhold/Disocactus_transcriptome#25]
**10% Organización del repositorio**
- [x] You have a folder figures for illustrations while figures are in [out](https://github.com/IsauraRReinhold/Disocactus_transcriptome/tree/master/out). I suggest putting graphics in the folder figures and renaming the other one "images" or simply leaving images in the same folder as the README as you did for[ project_info](https://github.com/IsauraRReinhold/Disocactus_transcriptome/tree/master/project_info).

- [x] In [BUSCO_summaries](https://github.com/IsauraRReinhold/Disocactus_transcriptome/tree/master/out/BUSCO_summaries) some tables are present twice, please eliminate the duplicates or clarify why two tables are present, renaming them accordingly.

**15% README (debe ser en inglés)**
- [x] Since your pipeline is quite long, a small diagram describing each step of your pipeline would be nice!

- [x] The script [15.quality_check_samples.sh](https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/bin/15.quality_check_samples.sh) is lacking in the list describing scripts in the README. 

- [x] Watch out for typos in English! 

**15% Análisis**
Well structured and clear - well done!

**15% Resumen y discusión en formato Markdown**
- [x] Missing so far

**15% Gráfica(s) en R**
- [x] In your R reports in markdown, it is nice to see the scripts used to generate the figures, unfortunately the figure itself doesn't load, for example in [dif_exp_DE.md](https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/out/dif_exp_DE/dif_exp_DE.md)

**15% Scripts deben estar comentados en inglés**
In general your scripts are well structured and documented. Well done!
Minor comments:
- [x] A few comments have been left in Spanish
- [x] Your R scripts are not numbered in [bin](https://github.com/IsauraRReinhold/Disocactus_transcriptome/tree/master/bin). I suggest following the same numeration (for example 16.1, 16.2 etc) to complete your pipeline
- [x] The working directory need to be set to source file at the beginning of the R scripts
- [x] Please use relative routes in [11.DE_abun_est.sh](https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/bin/11.DE_abun_est.sh)
- [x] In [busco_figure.r](https://github.com/IsauraRReinhold/Disocactus_transcriptome/blob/master/bin/busco_figure.r) some of the ggplot commands are duplicated

**15% Avances, organización y respuesta a comentarios en el proyecto de Github en inglés**
Good luck with the kegga issue! Let me know if you can't resolve it.

**Comment by IsauraRReinhold** [comment]
The busco_figure.r comes from the BUSCO program, I only modified some parts wich are indicated as comments in the script.

**Comment by IsauraRReinhold** [comment]
The numeration of the scripts was wrong, I modifed the numeration and the 14. script know is in the README

**Comment by IsauraRReinhold** [comment]
ITo improve my repository try to follow all the recommendations

1. I reordered all the figures and saved them in the info_project folder
2. The tables in the BUSCO_summary folder were explained in the README file.
3. I made a diagram to clarify my project called workflow
4. I reordered the scripts so that they were well numbered
5. the summary.md is saved in the info_project folder
6. the dif_exp_DE.md now has figures
7. All comments on my scripts are now in English.
8. R scripts are now numbered
9. I set workdir in my scripts
10. fixed absolute paths
11. The busco_figure.r is a script produced by the program, I only modified a few lines to reorder the colors and labels.

thanks for the comments, now my repository is much better.

**Comment by IsauraRReinhold** [comment]
Finally a check the typos in the README and summary

**Comment by camillethuyentruong** [comment]
Your repo, scripts and figures look great, well done!

To avoid using absolute path in your R scripts, it is common practice to set the working directory "to source file" so the script is reproducible for everyone.

I hope you enjoyed the course!
